### ISSUE TITLE
when call SetupMapper,it can't load and tips: "invalid argument"

### ISSUE THREAD

**Issue by yangni2017** [anatol/luks.go#7]
my code is as follows:
![image](https://user-images.githubusercontent.com/24664071/173567357-2d8fd2ba-fef4-4348-a027-5e79b54f4952.png)

exec result:
![image](https://user-images.githubusercontent.com/24664071/173567497-3c2b456c-0db1-4ff3-9ebc-ecf4a500f7f6.png)

it's can't work , because it unrecognizable the cmd : DM_TABLE_LOAD (0xc138fd09)
![image](https://user-images.githubusercontent.com/24664071/173567035-d4ea4fbf-639c-4b01-a69c-8656e99d77cf.png)

ioctl:
![image](https://user-images.githubusercontent.com/24664071/173567126-3bca1f56-e45f-4196-bbc9-45c5606da0ce.png)

why?

**Comment by anatol** [comment]
Also check kernel logs using `dmesg` as it might contain additional debug information.

**Comment by anatol** [comment]
I just added a test for `SetupVolume` and it works fine.

So check `dmesg` it will provide more information about this error. It could be a problem with the LUKS volume (e.g. it is too small).

Print content of the volume struct with `fmt.Printf("%+v\n", volume)` right before `SetupMapper()`. Also, print the device dump with `sudo cryptsetup luksDump /dev/sdb`. This will give you more information.

**Comment by yangni2017** [comment]
> I just added a test for `SetupVolume` and it works fine.
> 
> So check `dmesg` it will provide more information about this error. It could be a problem with the LUKS volume (e.g. it is too small).
> 
> Print content of the volume struct with `fmt.Printf("%+v\n", volume)` right before `SetupMapper()`. Also, print the device dump with `sudo cryptsetup luksDump /dev/sdb`. This will give you more information.

**dump info:**
#  cryptsetup luksDump /dev/sdb
LUKS header information for /dev/sdb

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha1
Payload offset: 4096
MK bits:        256
MK digest:      71 cc 0b cd a2 ce 80 9a ae cd 87 99 18 8e 6b df e0 45 77 90
MK salt:        40 7f c1 ae e8 7c c2 9f 0e 64 95 68 fd e5 22 20
                e4 11 b7 47 8a 1c 76 e7 42 e4 98 62 cc e3 d4 05
MK iterations:  89875
UUID:           3284a821-42de-4557-847c-ea45dfdcb3d8

Key Slot 0: ENABLED
        Iterations:             376469
        Salt:                   16 b2 ef f7 8d 04 89 f0 91 da 6e 21 7d 33 d6 67
                                2b 1a 33 b9 a2 f2 3d 68 13 18 72 ea 00 0c 26 8f
        Key material offset:    8
        AF stripes:             4000
Key Slot 1: DISABLED
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED


**the volume output as follow:**
volume = &{backingDevice:/dev/sdb flags:[no-read-workqueue no-write-workqueue] uuid:3284a821-42de-4557-847c-ea45dfdcb3d8 key:[4 116 80 150 14 114 234 58 127 84 197 160 100 57 18 237 82 118 221 98 107 39 87 91 177 47 40 140 75 55 147 60] luksType:LUKS1 storageEncryption:aes-xts-plain64 storageIvTweak:0 storageSectorSize:512 storageOffset:2097152 storageSize:10735321088}
cmd=0xc138fd03


**the dmeg output as follow:**
_Jun 15 09:30:36 qicheng kernel: [686367.269611] device-mapper: table: 252:0: crypt: Invalid feature arguments
Jun 15 09:30:36 qicheng kernel: [686367.270205] device-mapper: ioctl: error adding target to table_

**Comment by anatol** [comment]
The dmesg contains the reason: `table: 252:0: crypt: Invalid feature arguments`. The "feature" in this context is the list of dmcypt flags like `no_read_workqueue`. One of the flags is not recognized by your kernel.

Could you please modify the function `func (v *Volume) SetupMapper(name string)` and add `fmt.Printf("%+v\n", kernelFlags)` right before calling `devmapper.CreateAndLoad()`?

Also please tell me your Linux kernel version with `uname -a`?

**Comment by yangni2017** [comment]
> fmt.Printf("%+v\n", kernelFlags)

kernelFlags = [no_read_workqueue no_write_workqueue]

\# uname -a
Linux qicheng 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yangni2017** [comment]
could tell me which special options need to turn on in the kernel?

**Comment by anatol** [comment]
> > fmt.Printf("%+v\n", kernelFlags)
> 
> `kernelFlags = [no_read_workqueue no_write_workqueue]`
> 
> ```
> # uname -a
> Linux qicheng 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```

Alright I see the problem. flags FlagNoReadWorkqueue and FlagNoWriteWorkqueue were added to Linux only in 5.4. And your kernel is *really* old (4.4.0).

Please remove `dev.FlagsAdd(luks.FlagNoReadWorkqueue, luks.FlagNoWriteWorkqueue)` part from the code and the example should work.

**Comment by yangni2017** [comment]
it work well,thanks a lot.
